name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml

  lint:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Check TypeScript types
        run: bun run check

      - name: Check code formatting
        run: bun run format

