name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install package dependencies
        run: bun install

      # goal
      - name: Check TypeScript types
        run: bun run check

      - name: Check code formatting
        run: bun run format
