name: Prepare

on:
  workflow_call

jobs:
  prepare-ci-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install package dependencies
        run: bun install
