name: Test

on:
  pull_request:
    branches:
      - main

env:
  VITE_NEON_DB_URL: ${{ secrets.VITE_NEON_DB_URL }}
  VITE_NEON_DB_POOLER_URL: ${{ secrets.VITE_NEON_DB_POOLER_URL }}
  VITE_WSPROXY: ${{ vars.VITE_WSPROXY }}

jobs:
  test-node-18:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install package dependencies
        run: npm install

      # goal
      - name: Run tests in Node 18 (no native WebSocket), node environment
        run: npm run testNode

  test-node-lts:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install package dependencies
        run: npm install

      # goal
      - name: Run tests in Node LTS, node environment
        run: npm run testNode

      - name: Run tests in Node LTS, edge-runtime environment
        run: npm run testEdge

      - name: Run Chromium tests
        run: npm run testChromium

      - name: Run Cloudflare Workers tests
        run: npm run testCfWorker
