name: Test

on:
  pull_request:
    branches:
      - main

env:
  VITE_NEON_DB_URL: ${{ secrets.VITE_NEON_DB_URL }}
  VITE_NEON_DB_POOLER_URL: ${{ secrets.VITE_NEON_DB_POOLER_URL }}
  VITE_VERCEL_TOKEN: ${{ secrets.VITE_VERCEL_TOKEN }}
  VITE_CLERK_SECRET_KEY: ${{ secrets.VITE_CLERK_SECRET_KEY }}
  VITE_WSPROXY: ${{ vars.VITE_WSPROXY }}
  VITE_CLERK_USER: ${{ vars.VITE_CLERK_USER }}

jobs:
  test-node-old:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install package dependencies
        run: npm install

      # goal
      - name: Run CLI-based tests in Node 18 (no native WebSocket), node environment
        run: npm run test:node

  test-node-lts:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install package dependencies
        run: npm install

      # goal
      - name: Run all tests in Node LTS
        run: npm run test
