name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml

  test:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: bun run test
