name: Test

on:
  pull_request:
    branches:
      - main

env:
  VITE_NEON_DB_URL: ${{ secrets.VITE_NEON_DB_URL }}
  VITE_NEON_DB_POOLER_URL: ${{ secrets.VITE_NEON_DB_POOLER_URL }}
  VITE_VERCEL_TOKEN: ${{ secrets.VITE_VERCEL_TOKEN }}
  VITE_CLERK_SECRET_KEY: ${{ secrets.VITE_CLERK_SECRET_KEY }}
  VITE_WSPROXY: ${{ vars.VITE_WSPROXY }}
  VITE_CLERK_USER: ${{ vars.VITE_CLERK_USER }}

jobs:
  test-old:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install package dependencies
        run: |
          # strip Prisma, whose preinstall script throws on Node versions less than 18.x
          # and downgrade to vitest 2.x, which supports Node 16

          sudo apt-get install jq
          mv package.json package.json.old
          cat package.json.old \
            | jq '.devDependencies.vitest = "2.x"' \
            | jq 'del(.devDependencies.prisma,.devDependencies."@prisma/client",.devDependencies."@vitest/browser")' \
            > package.json
          cat package.json

          # then install

          npm install

      # goal
      - name: Using vitest@2, run CLI-based tests in Node 16
        run: npm run test:node

  test-current:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: denoland/setup-deno@v2
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install package dependencies
        run: npm install

      # goal
      - name: Run all tests
        run: npm run test
