name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install package dependencies
        run: bun install

      # goal
      - name: Run tests
        env:
          VITE_NEON_DB_URL: ${{ secrets.VITE_NEON_DB_URL }}
          VITE_WSPROXY: ${{ vars.VITE_WSPROXY }}
        run: bun run test
